### ISSUE TITLE
حل تمرین ها

### ISSUE THREAD

**Issue by rmsod** [omidedriss/TeamOrbitSoft#4]

**Comment by amanehsalimi** [comment]
کپسولی بودن یعنی رفتار یک شی از دید کاربر پنهان باشد، به عبارتی کاربر از آنچه درون آن شی اتفاق می افتد تا درخواستش را 
انجام دهد مطلع نیست.

چند شکلی بودن به این معنی است که یک شی از کالس فرزند بتواند در مواقعی که به یک شی از کالس پدر نیاز است همانند شی
ای از کالس پدر عمل کند به عبارتی شی از کالس فرزند، شی از کالس پدر نیز میتواند باشد اما عکس آن درست نیست

**Comment by rmsod** [comment]
مختصری راجع به کپسوله سازی و پلی مورفی در جاوا
تمرین کلاس اندروید مظاهری 20/05/1401


کپسوله سازی در جاوا
کپسول‌سازی در جاوا فرآیندی است که کد و داده‌ها را با هم در یک واحد قرار می‌دهد، و تا حد امکان داده ها و کنش های اطلاعات بصورت مجتمع و مستقل در یک پکیج گردآوری شود.ما می توانیم با خصوصی کردن تمام اعضای داده کلاس، یک کلاس کاملاً کپسوله شده در جاوا ایجاد کنیم.  از متدهای setter و getter برای تنظیم و دریافت داده در آن استفاده کنیم.
 به فرایند قرار دادن کدها و اطلاعات در واحدهای یکتا گفته می شود.  شما هم می توانید با تبدیل سطح دسترسی تمام متغیرهای نمونه و متدهای یک کلاس به private . و برای دسترسی به متغییرهای خصوصی از متد های getter و setter  استفاده میکنیم .
متدهای getter و setter
اصولا برنامه نویسان جاوا متغیرهای نمونه (متغیرهایی که در بدنه کلاس تعریف می شوند و نه متد) را به صورت private تعریف می کنند. این امر سبب می شود که سایر کلاس ها و متدهای آنها به راحتی نتوانند مقدار این متغیرها را تغییر دهند. در عوض آنها مجبورند که از متدهای getter و setter که سطح دسترسی public دارند برای مقدار دهی و دستیابی به مقادیر متغیرهای نمونه استفاده کنند. ممکن است از خودتان بپرسید خوب چه فرقی می کند که متغیرهای نمونه را مستقیما مقدار دهی کنم یا از متدهاد getter و setter استفاده کنم؟
جواب این است که شما با استفاده از متدهای getter و setter می توانید مقادیری که به متغیرهای نمونه ارسال می شود را کنترل کنید و از ارسال و دریافت ورودی هایی که معتبر نیستند جلوگیری کنید. فرض کنید می خواهید در نرم افزارتان سن کاربر را دریافت کنید. آن شخص یک عدد منفی را در نرم افزار وارد می کند و خوب همه می دانیم که سن یک شخص نمی تواند منفی باشد. اینجاست که باید پیام خطایی را به کاربر نمایش دهیم و به او بگوییم که سن خود را درست وارد نکرده است. این اتفاق از طریق قوانینی که در متد setter خودمان تعیین کرده ایم اتفاق می افتد. حال تصور کنید اگر سطح دسترسی public به متغیر نمونه خود داده بودیم چه اتفاقی می افتاد، مقدار منفی به جای سن آن شخص به راحتی قرار می گرفت!
پلی مورفیسم
اگر یک کار به روش های مختلف انجام شود، به آن چند شکلی می گویند. در جاوا برای رسیدن به چند شکلی از روش overloading و روش overriding استفاده می کنیم.اشیا در جاوا ممکن است ابعاد مختلفی داشته باشند. 
در زندگی واقعی یک فرد می‌تواند روابط گوناگونی با افراد مختلف داشته و در برابر هر فرد دیگری جایگاه متفاوتی داشته باشد. یک زن می‌تواند همزمان مادر، دختر، خواهر ، داشجو باشد یعنی در برابر هر کدام از این افراد رفتار متفاوتی داشته باشد.
مثال چند ریختی در جاوا
در این مثال، یک کلاس والد (Superclass) به نام «Shapes» وجود دارد که دارای متُدی به نام «()area» است. کلاس واحد «Shapes» می‌تواند مثلث، دایره، مستطیل و اشکال دیگری داشته باشد. هر کلاس فرزند یا زیر کلاس (subclass) دارای روش مخصوص به خود برای محاسبه مساحت هستند که آن را در خروجی چاپ می‌کنند. با استفاده از وراثت و چند ریختی، کلاس‌های فرزند می‌توانند از متد «()area» جهت یافتن فرمول مورد نظر برای شکل خود استفاده کنند.

class Shape  } 
  public void area()  {
    System.out.println("The formula for area of ");
}
}
class Triangle extends Shapes  } 
  public void area()  {
    System.out.println("Triangle is ½ * base * height ");
{
{
class Circle extends Shapes{
  public void area()  {
    System.out.println("Circle is 3.14 * radius * radius ");
{
{
class Main {
  public static void main(String[] args) }
    Shapes myShape = new Shapes();  // Create a Shapes object
    Shapes myTriangle = new Triangle();  // Create a Triangle object
    Shapes myCircle = new Circle();  // Create a Circle object
    myShape.area();
    myTriangle.area();
    myShape.area();
    myCircle.area();
{
}
